export const environment = {
  production: true,
  baseUrl: 'https://dev.joinaroom.live',
  login: '/auth/login',
  register: '/auth/register',
  forgot: '/auth/forgot/password',
  reset: '/auth/reset/password',
  checkUser: '/users/user-exists',
  userInfo: '/auth/info',
  rooms: '/events',
  myEvents: '/events/my-events',
  twilioToken: '/twilio-api/access-token',
  requestPayment: '/order/pay',
  confirmPayment: '/order/confirm-payment',
  payDetails: '/payment/details',
  getPayDetails: '/payment/payment-details',
  requestPayout: '/payment/payouts',
  confirmPayout: '/payment/confirm/payouts',
  payPalBalance: '/payment/payout/amount',
  firebaseConfig : {
    apiKey: 'AIzaSyA5tylH8P8VTzNmj-b9GI3mr_y1wuibNIk',
    authDomain: 'joinaroom-64fd4.firebaseapp.com',
    databaseURL: 'https://joinaroom-64fd4.firebaseio.com',
    projectId: 'joinaroom-64fd4',
    storageBucket: 'joinaroom-64fd4.appspot.com',
    messagingSenderId: '1083370687682',
    appId: '1:1083370687682:web:2c02e6eeb3cd23d8677f5b',
    measurementId: 'G-81D2NQC8XW'
  },
  merchantInfo: '/merchant/info',
  merchantLinks: '/merchant/links',
  cashOutRequest: '/approve-payments',
  allUserEvents: '/events/all-payment-events'
};
